[tool.djlint]
indent = "2"
max_line_length = "79"
preserve_blank_lines = true
profile = "django" 

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79
known_local_folder = ["api", "posts"]