# Generated by Django 4.2 on 2023-04-19 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="modl",
            new_name="Модель оборудования",
        ),
    ]
