# Generated by Django 4.2 on 2023-04-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="modl",
        ),
        migrations.AddField(
            model_name="modl",
            name="model_type",
            field=models.CharField(
                choices=[("ls", "Лазер"), ("pl", "Плазма"), ("wd", "Сварка")],
                default="ls",
                max_length=10,
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="Модель оборудования",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="products.modl",
            ),
        ),
        migrations.AlterField(
            model_name="modl",
            name="company_name",
            field=models.CharField(
                max_length=200, verbose_name="Имя компании"
            ),
        ),
        migrations.AlterField(
            model_name="modl",
            name="model_name",
            field=models.CharField(max_length=500, verbose_name="Имя модели"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Имя продукта"
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
