# Generated by Django 4.2 on 2023-04-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_modl_product_модель_оборудования"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Имя продукта"
            ),
        ),
    ]
