# Generated by Django 4.2 on 2023-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modl",
            old_name="company_name",
            new_name="Имя компании",
        ),
        migrations.AddField(
            model_name="modl",
            name="model_type",
            field=models.CharField(
                choices=[("ls", "Лазер"), ("pl", "Плазма"), ("wd", "Сварка")],
                default="ls",
                max_length=10,
            ),
        ),
    ]
