# Generated by Django 4.2 on 2023-04-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_company_name_modl_имя_компании_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="model_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="Модель оборудования",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="products.modl",
            ),
        ),
    ]
