# Generated by Django 4.2 on 2023-04-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_modl_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="company_name",
            field=models.CharField(
                choices=[("ht", "Hypertherm"), ("ct", "Centricut")],
                max_length=200,
                null=True,
                verbose_name="Имя компании",
            ),
        ),
        migrations.AlterField(
            model_name="modl",
            name="model_type",
            field=models.SlugField(
                choices=[("ls", "Лазер"), ("pl", "Плазма"), ("wd", "Сварка")],
                default="ls",
                max_length=10,
                verbose_name="Тип",
            ),
        ),
    ]
