# Generated by Django 4.2 on 2023-04-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_modl_model_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="Имя компании",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Company",
                to="products.company",
            ),
        ),
    ]
