# Generated by Django 4.2 on 2023-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_modl_model_name_alter_modl_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="modl",
            name="model_slug",
            field=models.SlugField(
                null=True, verbose_name="Сссылка на модель"
            ),
        ),
        migrations.AlterField(
            model_name="modl",
            name="model_name",
            field=models.CharField(max_length=500, verbose_name="Имя модели"),
        ),
    ]
