# Generated by Django 4.2 on 2023-04-19 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_rename_имя_компании_modl_company_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modl",
            old_name="company_name",
            new_name="Имя компании",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="modl",
            new_name="Модель оборудования",
        ),
    ]
