# Generated by Django 4.2 on 2023-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0010_remove_modl_имя_компании_modl_company_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="company_name",
            field=models.CharField(
                default="Hyperterm",
                max_length=500,
                verbose_name="Компания, которой принадлежит модель",
            ),
        ),
    ]
