# Generated by Django 4.2 on 2023-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_modl_model_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="model_slug",
            field=models.SlugField(
                blank=True,
                help_text="Ссылка, по которой будут доступны расходники к модели (можно оставить пустым)",
                unique=True,
                verbose_name="Ссылка на модель",
            ),
        ),
        migrations.AlterField(
            model_name="modl",
            name="model_type",
            field=models.CharField(
                choices=[("ls", "Лазер"), ("pl", "Плазма"), ("wd", "Сварка")],
                default="ls",
                help_text="На какой странице нужно отображать модель",
                max_length=10,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                help_text="Изображение расходника",
                null=True,
                upload_to="products/",
                verbose_name="Изображение",
            ),
        ),
    ]
