# Generated by Django 4.2 on 2023-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0011_alter_modl_model_slug_alter_modl_model_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="company_name",
            field=models.CharField(
                blank=True,
                choices=[("ht", "Hypertherm"), ("ct", "Centricut")],
                max_length=200,
                null=True,
                verbose_name="Имя компании",
            ),
        ),
    ]
