# Generated by Django 4.2 on 2023-04-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_company_remove_modl_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modl",
            name="Имя компании",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="products.company",
            ),
        ),
    ]
