# Generated by Django 4.2 on 2023-08-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0013_modl_show_in_psk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'company_name',
                    models.CharField(
                        max_length=200, verbose_name='Имя компании'
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name='modl',
            options={'verbose_name': 'Модели'},
        ),
        migrations.RemoveField(
            model_name='modl',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='modl',
            name='model_type',
            field=models.CharField(
                choices=[('ls', 'Лазер'), ('pl', 'Плазма'), ('wd', 'Сварка')],
                default='ls',
                help_text='На какой странице будет отображаться модель',
                max_length=10,
                verbose_name='Тип',
            ),
        ),
        migrations.AddField(
            model_name='modl',
            name='Имя компании',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='products.company',
            ),
            preserve_default=False,
        ),
    ]
