# Generated by Django 4.2 on 2023-04-20 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_modl_имя_компании"),
    ]

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="modl",
            name="model_type",
        ),
        migrations.AlterField(
            model_name="modl",
            name="Имя компании",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="products.company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="Тип",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_types",
                to="products.types",
            ),
        ),
        migrations.AddField(
            model_name="modl",
            name="Тип модели",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modl_types",
                to="products.types",
            ),
        ),
    ]
