# Generated by Django 4.2 on 2023-08-19 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'products',
            '0014_company_alter_modl_options_remove_modl_company_name_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании'},
        ),
    ]
