# Generated by Django 4.2 on 2023-08-19 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0016_types_remove_modl_model_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Типы оборудования'},
        ),
    ]
