# Generated by Django 4.2 on 2023-08-19 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0017_rename_types_type_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Модель оборудования',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='products.modl',
            ),
        ),
    ]
