# Generated by Django 4.2 on 2023-08-19 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0018_alter_product_модель_оборудования'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RemoveField(
            model_name='modl',
            name='Тип модели',
        ),
        migrations.AddField(
            model_name='modl',
            name='model_type',
            field=models.CharField(
                choices=[('ls', 'Лазер'), ('pl', 'Плазма'), ('wd', 'Сварка')],
                default='ls',
                help_text='На какой странице будет отображаться модель',
                max_length=10,
                verbose_name='Тип',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='Модель оборудования',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='products.modl',
            ),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
