# Generated by Django 4.2 on 2023-08-19 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'products',
            '0019_alter_company_options_remove_modl_тип_модели_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании'},
        ),
    ]
