# Generated by Django 4.2 on 2023-08-19 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0021_type_alter_modl_model_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Типы оборудования'},
        ),
    ]
