# Generated by Django 4.2 on 2023-08-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0022_alter_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_name_russian',
            field=models.CharField(
                default=1,
                max_length=50,
                verbose_name='Название типа на русском',
            ),
            preserve_default=False,
        ),
    ]
