# Generated by Django 4.2 on 2023-08-20 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0023_type_type_name_russian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modl',
            old_name='model_type',
            new_name='Тип оборудования',
        ),
    ]
