# Generated by Django 4.2 on 2023-08-20 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0024_rename_model_type_modl_тип_оборудования'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modl',
            old_name='Имя компании',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='modl',
            old_name='Тип оборудования',
            new_name='model_type',
        ),
    ]
