# Generated by Django 4.2 on 2023-08-20 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0025_rename_имя_компании_modl_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modl',
            old_name='company_name',
            new_name='Компания',
        ),
        migrations.RenameField(
            model_name='modl',
            old_name='model_type',
            new_name='Тип_модели',
        ),
    ]
