# Generated by Django 4.2 on 2023-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0026_rename_company_name_modl_компания_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Доступные типы',
            field=models.ManyToManyField(to='products.type'),
        ),
    ]
