# Generated by Django 4.2 on 2023-08-20 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0027_company_доступные_типы'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Доступные типы',
        ),
    ]
