# Generated by Django 4.2 on 2023-08-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0028_remove_company_доступные_типы'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Модель оборудования',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='products.modl',
            ),
        ),
    ]
