# Generated by Django 4.2 on 2023-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0030_alter_product_модель_оборудования'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='available_types',
            field=models.ManyToManyField(
                to='products.type', verbose_name='Доступные типы'
            ),
        ),
    ]
