# Generated by Django 4.2 on 2023-08-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0031_company_available_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='available_types',
            field=models.ManyToManyField(
                related_name='companys',
                to='products.type',
                verbose_name='Доступные типы',
            ),
        ),
    ]
