# Generated by Django 4.2 on 2023-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0032_alter_company_available_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.SlugField(
                max_length=200, verbose_name='Имя компании'
            ),
        ),
    ]
