# Generated by Django 4.2 on 2023-08-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0033_alter_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modl',
            name='Компания',
        ),
        migrations.RemoveField(
            model_name='modl',
            name='Тип_модели',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Модель оборудования',
        ),
        migrations.AddField(
            model_name='modl',
            name='company_name',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='products.company',
                verbose_name='Компания',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modl',
            name='model_type',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='models',
                to='products.type',
                verbose_name='Тип модели',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modl',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='products.modl',
                verbose_name='Модель оборудования',
            ),
            preserve_default=False,
        ),
    ]
