# Generated by Django 3.2.16 on 2023-10-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_modl_компания_remove_modl_тип_модели_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modl',
            name='show_in_psk',
        ),
    ]
